/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FolderItem: (typeof import('./src/components/FolderItem.vue'))['default'];
    FoldersTree: (typeof import('./src/components/FoldersTree.vue'))['default'];
    FoldersTreeWrapper: (typeof import('./src/components/FoldersTreeWrapper.vue'))['default'];
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default'];
    HelloWorldVite: (typeof import('./src/components/HelloWorldVite.vue'))['default'];
    TaskForm: (typeof import('./src/components/TaskForm.vue'))['default'];
  }
}
