/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FolderItem: typeof import('./src/components/molecules/FolderItem.vue')['default'];
    FoldersTree: typeof import('./src/components/atoms/FoldersTree.vue')['default'];
    FoldersTreeWrapper: typeof import('./src/components/molecules/FoldersTreeWrapper.vue')['default'];
    FormController: typeof import('./src/components/organisms/FormController.vue')['default'];
  }
}
