services:
  postgres:
    image: postgres:16
    container_name: ntt-test-task-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ntt-test-task-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    depends_on:
      - postgres

  go-server:
    container_name: ntt-test-task-go-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    environment:
      - SERVER_PORT=${API_SERVER_PORT}
    volumes:
      - ./.env:/.env
      - ./backend/data.json:/data.json
    depends_on:
      - postgres

volumes:
  postgres_data:
